name: Unit Tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        npm install

    - name: Build Library
      run: |
        npm run build

    - name: Run Tests
      run: |
        npm test

    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#00C07F"
        message: "https://github.com/openfl/openfl-js/actions\nUnit tests succeeded."

    - name: Notify Discord (failure)
      uses: appleboy/discord-action@master
      if: failure()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#FF6562"
        message: "https://github.com/openfl/openfl-js/actions\nUnit tests failed."

